
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Map = lazy(() => import("./pages/Map.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const ResetPassword = lazy(() => import("./pages/ResetPassword.tsx"));
const Signup = lazy(() => import("./pages/Signup.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/forgot-password", element: <ForgotPassword />},
	{ path: "/forgotpassword", element: <ForgotPassword />},
	{ path: "/login", element: <Login />},
	{ path: "/map", element: <Map />},
	{ path: "/profile", element: <Profile />},
	{ path: "/reset-password", element: <ResetPassword />},
	{ path: "/resetpassword", element: <ResetPassword />},
	{ path: "/signup", element: <Signup />},

];
